import * as THREE from 'three';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<div id="game"></div><div id="vignette"></div><div id="grain"></div><div id="hud"><div class="top"><div class="brand">ПОСЛЕ СИГНАЛА<small>AFTER THE SIGNAL · 01</small></div><div class="topright"><div class="chip" id="weather">☁ ТУМАН · 06:42</div><div class="chip" id="status">СОХРАНЕНО</div></div></div><div class="chapter"><div class="eyebrow" id="chapter">ГЛАВА I / ПОСЛЕДНИЙ ЭФИР</div><h2 id="objective-title">Найти радиостанцию</h2><p id="objective">Следуй по старой дороге на запад. У башни должен быть работающий передатчик.</p></div><div class="meters"><div class="meter-label"><span>ЗДОРОВЬЕ</span><span id="hp-number">100</span></div><div class="meter health"><span id="hp-bar" style="width:100%"></span></div><div class="meter-label"><span>ВЫНОСЛИВОСТЬ</span><span id="st-number">100</span></div><div class="meter"><span id="st-bar" style="width:100%"></span></div><div class="inventory"><div class="slot">ПАТРОНЫ<b id="ammo">6 / 18</b></div><div class="slot">БИНТЫ<b id="bandages">2</b></div><div class="slot">ПРИПАСЫ<b id="supplies">0</b></div></div></div><div class="crosshair"></div><div class="subtitle" id="subtitle"></div><div class="prompt" id="prompt" style="display:none"></div><div class="toast" id="toast"></div></div><div id="touch"><div id="stick"><div id="knob"></div></div><div id="actions"><button class="action" data-key="c">ТИХО</button><button class="action" data-key="e">ВЗЯТЬ</button><button class="action" data-key="h">БИНТ</button><button class="action big" data-key="fire">ОГОНЬ</button></div><div class="mobile-top"><button class="action" data-key="r">ПЕРЕЗ.</button><button class="action" data-key="run">БЕГ</button><button class="action" data-key="m">КАРТА</button></div></div><div id="fade"></div><div id="letter"><div class="paper"><h3 id="letter-title"></h3><div id="letter-text"></div><button id="close-letter">ЗАКРЫТЬ · E</button></div></div><div class="menu" id="menu"><div class="menu-inner"><div class="overline">ОРИГИНАЛЬНАЯ ИСТОРИЯ О ТОМ, ЧТО ОСТАЁТСЯ</div><h1>ПОСЛЕ<br><em>СИГНАЛА</em></h1><div class="en">AFTER THE SIGNAL</div><div class="divider"></div><p>В штате Орегон погасли маяки. Бывший техник связи Мара Рид и её младший брат Итан ищут источник последнего радиосигнала. За лесом кто-то ещё зовёт на помощь.</p><button id="start" class="primary">НАЧАТЬ ИСТОРИЮ →</button><p class="hint">WASD — движение · Мышь — обзор · ЛКМ — выстрел · Shift — бег · C — присесть · E — взаимодействие · R — перезарядка · H — лечение · M — карта<br>На телефоне: левый джойстик, свайп справа и экранные кнопки. Наушники рекомендуются.</p></div></div>`;
const $=id=>document.getElementById(id), clamp=THREE.MathUtils.clamp;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9da79b);scene.fog=new THREE.FogExp2(0x9da79b,.017);
const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,330);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;$('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xb8cbca,0x344332,2.5));const sun=new THREE.DirectionalLight(0xffd5a0,3.3);sun.position.set(-45,70,-75);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;sun.shadow.bias=-.0004;scene.add(sun);
const mat=(c,rough=1,metal=0)=>new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal});
const M={ground:mat(0x556651),road:mat(0x66635b),bark:mat(0x403e32),pine:mat(0x304d3c),pine2:mat(0x49614b),grass:mat(0x758068),concrete:mat(0x777a70),wall:mat(0x86877b),roof:mat(0x383f3c),rust:mat(0x8d5b42),yellow:mat(0xc6a15e),red:mat(0x9b614e),glass:mat(0x6d938f,.15,.3),dark:mat(0x252e2b),skin:mat(0xb99177),coat:mat(0x455a54),denim:mat(0x384955),infected:mat(0x747f69),light:new THREE.MeshStandardMaterial({color:0xffcd73,emissive:0xffb659,emissiveIntensity:2})};
const cubeGeo=new THREE.BoxGeometry(1,1,1), cylGeo=new THREE.CylinderGeometry(1,1,1,8), sphereGeo=new THREE.SphereGeometry(1,10,8);
function box(parent,x,y,z,w,h,d,m,shadow=true){let o=new THREE.Mesh(cubeGeo,m);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o}
function cylinder(parent,x,y,z,rt,rb,h,m){let o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,7),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o}
function ball(parent,x,y,z,sx,sy,sz,m){let o=new THREE.Mesh(sphereGeo,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;parent.add(o);return o}
let seed=82771;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function between(a,b){return a+rand()*(b-a)}
const ground=box(scene,0,-.35,-45,230,.7,260,M.ground,false);const road=box(scene,0,.01,-39,7,.06,210,M.road,false);
for(let i=0;i<95;i++){let z=between(-138,62),x=between(-2.5,2.5);box(scene,x,.05,z,between(.1,.5),.015,between(.4,2),rand()>.5?M.concrete:M.ground,false)}
// Instancing keeps the forest to five draw calls even on mobile GPUs.
const forest=[];for(let i=0;i<410;i++){let x=between(-108,108),z=between(-160,80);if(Math.abs(x)<9||Math.hypot(x+30,z+25)<15||Math.hypot(x-25,z+64)<17||Math.hypot(x,z+114)<18)continue;forest.push([x,z,between(.65,1.45)])}
const dummy=new THREE.Object3D();function instanced(geo,material,count,fn){let mesh=new THREE.InstancedMesh(geo,material,count);mesh.castShadow=count<500;mesh.receiveShadow=count<500;for(let i=0;i<count;i++){let [x,y,z,sx,sy,sz]=fn(i);dummy.position.set(x,y,z);dummy.scale.set(sx,sy,sz);dummy.rotation.set(0,0,0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)}mesh.instanceMatrix.needsUpdate=true;scene.add(mesh);return mesh}
instanced(new THREE.CylinderGeometry(.23,.32,4,6),M.bark,forest.length,i=>{let [x,z,s]=forest[i];return[x,2*s,z,s,s,s]});
for(let j=0;j<3;j++)instanced(new THREE.ConeGeometry(1.5-j*.24,3.5-j*.2,7),j%2?M.pine:M.pine2,forest.length,i=>{let[x,z,s]=forest[i];return[x,(3.8+j*1.15)*s,z,s,s,s]});
const grasses=[];for(let i=0;i<600;i++){let x=between(-105,105),z=between(-154,75);if(Math.abs(x)<4)continue;grasses.push([x,z,between(.35,.95),between(.1,.3)])}
instanced(new THREE.ConeGeometry(1,1,3),M.grass,grasses.length,i=>{let[x,z,h,r]=grasses[i];return[x,h*.5,z,r,h,r]});
function ruin(x,z,w,d,rot=0){let g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);box(g,0,.15,0,w,.3,d,M.concrete);let h=between(2.6,4);box(g,-w/2,h/2,0,.35,h,d,M.wall);box(g,w/2,h/2,-d*.27,.35,h,d*.46,M.wall);box(g,w/2,h/2,d*.33,.35,h,d*.35,M.wall);box(g,0,h/2,-d/2,w,h,.35,M.wall);box(g,-w*.2,h-.2,0,w*.62,.3,d*.73,M.roof);for(let j=0;j<4;j++)box(g,between(-w*.35,w*.35),.3,between(-d*.32,d*.32),between(.4,1.3),between(.3,.7),between(.4,.9),j%2?M.rust:M.concrete);return g}
ruin(-31,-25,14,11,.24);ruin(25,-64,17,13,-.2);ruin(-19,-90,11,10,.32);ruin(17,-20,10,9,-.3);ruin(-28,-119,11,12,.1);
for(let i=0;i<35;i++){let x=between(-65,65),z=between(-130,43);if(Math.abs(x)<5)continue;box(scene,x,.25,z,between(.35,1.5),between(.4,1),between(.4,1.4),i%3?M.concrete:M.rust)}
// Silent, ruined relay tower: an unambiguous destination visible through the fog.
const tower=new THREE.Group();tower.position.set(0,0,-116);scene.add(tower);for(let i=0;i<4;i++){let a=i*Math.PI/2;cylinder(tower,Math.cos(a)*3,12,Math.sin(a)*3,.13,.26,24,M.rust)}for(let y=4;y<23;y+=4){box(tower,0,y,0,6.2,.12,.18,M.rust);box(tower,0,y,0,.18,.12,6.2,M.rust)}cylinder(tower,0,25,0,.12,.12,8,M.concrete);ball(tower,0,29,0,.4,.4,.4,M.light);
for(let i=0;i<26;i++){let z=-133+i*8;for(let side of [-1,1]){let x=side*4.7;box(scene,x,1.5,z,.17,3,.17,M.bark);if(i%3===0)box(scene,x,2.8,z,.45,.28,.35,M.yellow)}}
function car(x,z,rotation=0){let g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;scene.add(g);box(g,0,.75,0,2.25,.85,4.5,M.rust);box(g,0,1.45,-.35,1.88,.7,2.6,M.dark);box(g,0,1.5,-1.68,1.72,.53,.08,M.glass);for(let a of [-1,1])for(let b of [-1,1]){let w=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.15,12),M.dark);w.rotation.z=Math.PI/2;w.position.set(a*1.15,.43,b*1.4);g.add(w)}return g}car(1.5,-36,.25);car(-1.8,-93,-.3);
function human(coat,infected=false){let g=new THREE.Group();let torso=box(g,0,1.17,0,.68,.91,.39,coat);let head=ball(g,0,1.94,-.03,.28,.3,.27,infected?M.infected:M.skin);box(g,0,2.14,-.06,.58,.17,.54,infected?M.pine:M.dark);let legs=[];for(let x of [-.19,.19]){let leg=box(g,x,.45,0,.25,.87,.26,M.denim);legs.push(leg)}let arms=[];for(let x of [-.46,.46]){let arm=box(g,x,1.19,.02,.2,.77,.24,coat);arms.push(arm)}return{g,legs,arms,head,torso}}
const pmodel=human(M.coat);scene.add(pmodel.g);const companion=human(M.yellow);scene.add(companion.g);companion.g.scale.setScalar(.89);
const enemies=[];function spawnEnemy(x,z,type='drifter'){let model=human(type==='runner'?M.rust:M.infected,true);model.g.position.set(x,0,z);scene.add(model.g);enemies.push({model,x,z,hp:type==='runner'?55:85,type,state:'idle',target:null,lastSeen:0,attack:0,phase:rand()*8,home:{x,z},alive:true});}
for(let [x,z,t] of [[-9,-5,'drifter'],[9,-15,'drifter'],[-25,-15,'runner'],[-20,-38,'drifter'],[-38,-30,'drifter'],[12,-45,'runner'],[28,-48,'drifter'],[18,-75,'runner'],[-9,-83,'drifter'],[-23,-103,'drifter'],[13,-100,'runner'],[-8,-120,'runner'],[8,-124,'drifter']])spawnEnemy(x,z,t);
const interactables=[];function marker(x,z,color=0xffca74){let g=new THREE.Group();g.position.set(x,0,z);scene.add(g);let ring=new THREE.Mesh(new THREE.TorusGeometry(.8,.045,6,24),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8}));ring.rotation.x=-Math.PI/2;ring.position.y=.12;g.add(ring);let beam=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,2.1,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.55}));beam.position.y=1.2;g.add(beam);return g}
function loot(x,z,kind){let g=new THREE.Group();g.position.set(x,0,z);scene.add(g);box(g,0,.2,0,.55,.38,.48,kind==='ammo'?M.rust:M.yellow);let glow=marker(x,z,kind==='ammo'?0xf4ae8b:0xc7dca2);interactables.push({x,z,kind,mesh:g,glow,active:true})}
for(let [x,z,k] of [[6,4,'ammo'],[-11,-12,'supplies'],[-29,-28,'note'],[-36,-18,'bandage'],[24,-61,'medicine'],[32,-66,'ammo'],[-18,-91,'supplies'],[8,-103,'bandage'],[0,-116,'tower']]){if(k==='note'||k==='medicine'||k==='tower'){let glow=marker(x,z);interactables.push({x,z,kind:k,glow,active:true})}else loot(x,z,k)}
const state={started:false,ended:false,paused:false,stage:0,x:0,z:26,yaw:Math.PI,pitch:.12,hp:100,stamina:100,ammo:6,reserve:18,bandages:2,supplies:0,crouch:false,aim:false,shotTime:0,reload:0,hitTime:0,time:0,dialogTime:0,alert:0,noise:0,companionAlive:true,choice:null,step:0};const keys={};let joy={x:0,y:0},lookTouch=null,audio=null,ambient=null;
function save(){try{localStorage.setItem('ats-save',JSON.stringify({stage:state.stage,x:state.x,z:state.z,hp:state.hp,ammo:state.ammo,reserve:state.reserve,bandages:state.bandages,supplies:state.supplies,companionAlive:state.companionAlive,choice:state.choice,looted:interactables.map(a=>a.active)}))}catch{}}
function load(){try{let v=JSON.parse(localStorage.getItem('ats-save'));if(!v)return false;for(let k of ['stage','x','z','hp','ammo','reserve','bandages','supplies','companionAlive','choice'])if(v[k]!==undefined)state[k]=v[k];v.looted?.forEach((v,i)=>{if(interactables[i]&&!v){interactables[i].active=false;interactables[i].glow.visible=false;interactables[i].mesh?.removeFromParent()}});return true}catch{return false}}
function subtitle(who,text,duration=5){$('subtitle').innerHTML=`<span class="speaker">${who}:</span> ${text}`;state.dialogTime=duration}
function toast(text){$('toast').textContent=text;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').textContent='',2200)}
function sound(freq=190,dur=.1,type='triangle',gain=.08){if(!audio)return;let o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.45),audio.currentTime+dur);v.gain.setValueAtTime(gain,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function initAudio(){try{audio=new (window.AudioContext||window.webkitAudioContext)();const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.025)*.995;data[i]=last}let src=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();src.buffer=buffer;src.loop=true;filter.type='lowpass';filter.frequency.value=410;gain.gain.value=.15;src.connect(filter).connect(gain).connect(audio.destination);src.start();ambient={filter,gain}}catch{}}
function updateObjective(){const data=[['Найти радиостанцию','Исследуй заброшенную станцию к западу от дороги и найди запись оператора.'],['Достать лекарство','Итану становится хуже. Найди аптечку в бывшей клинике к востоку от дороги.'],['Добраться до ретранслятора','Отнеси лекарство к северной вышке и передай сообщение.'],['Свободное исследование','Сигнал отправлен. Исследуй лес, собери припасы и постарайся выжить.']];let [title,desc]=data[Math.min(state.stage,3)];$('objective-title').textContent=title;$('objective').textContent=desc;$('chapter').textContent=state.stage>=3?'ЭПИЛОГ / ТИХИЙ ЭФИР':'ГЛАВА I / ПОСЛЕДНИЙ ЭФИР'}
function readLetter(title,text,callback){state.paused=true;$('letter').style.display='flex';$('letter-title').textContent=title;$('letter-text').innerHTML=text;$('close-letter').onclick=()=>{$('letter').style.display='none';state.paused=false;callback?.()}}
function finish(){state.stage=3;save();readLetter('ПОСЛЕДНИЙ ЭФИР','«Если вы меня слышите, значит мы ещё здесь».<br><br>Мара включает передатчик. В статике на секунду слышится ответ: «Убежище Блэк-Пойнт. Мы видим ваш свет».<br><br>Итан улыбается впервые за несколько дней. Они не знают, кто ждёт их по ту сторону леса. Но сегодня они дошли вместе.<br><br><strong>КОНЕЦ ПЕРВОЙ ГЛАВЫ · СВОБОДНОЕ ИССЛЕДОВАНИЕ ОТКРЫТО</strong>',()=>{subtitle('Итан','Значит, нам снова есть куда идти.',6);updateObjective()})}
function interact(){if(state.paused){$('close-letter').click();return}let closest=null,dist=3.1;for(let a of interactables){if(!a.active||((a.kind==='medicine'&&state.stage!==1)||(a.kind==='tower'&&state.stage!==2)))continue;let d=Math.hypot(state.x-a.x,state.z-a.z);if(d<dist){dist=d;closest=a}}if(!closest)return;let a=closest;if(a.kind==='note'){a.active=false;a.glow.visible=false;readLetter('ЗАПИСЬ ОПЕРАТОРА · 17 ОКТЯБРЯ','«Передатчик на северной вышке всё ещё работает. Я слышал Блэк-Пойнт, но не смог разобрать частоту. В клинике лежит последняя упаковка антибиотиков. Если придут люди с больным ребёнком — пусть возьмут. Это важнее моего эфира».',()=>{state.stage=1;updateObjective();subtitle('Мара','Аптека. Итан, держись. Я скоро вернусь.',6);save()})}else if(a.kind==='medicine'){a.active=false;a.glow.visible=false;state.stage=2;updateObjective();subtitle('Итан','Ты нашла? ... Я знал, что найдёшь.',6);save()}else if(a.kind==='tower'){a.active=false;a.glow.visible=false;finish()}else{a.active=false;a.glow.visible=false;a.mesh.removeFromParent();if(a.kind==='ammo'){state.reserve+=8;toast('+ 8 ПАТРОНОВ')}if(a.kind==='bandage'){state.bandages++;toast('+ 1 БИНТ')}if(a.kind==='supplies'){state.supplies++;toast('+ ПРИПАСЫ')}sound(650,.22);save()}}
function fire(){if(!state.started||state.paused||state.ended||state.reload>0||state.shotTime>0)return;if(state.ammo<=0){sound(130,.08);toast('ПУСТО · R ПЕРЕЗАРЯДИТЬ');return}state.ammo--;state.shotTime=.42;state.noise=18;state.alert=2;sound(95,.22,'sawtooth',.21);sound(700,.08,'square',.06);let target=null,best=.19;for(let e of enemies){if(!e.alive)continue;let dx=e.x-state.x,dz=e.z-state.z,dist=Math.hypot(dx,dz);if(dist>45)continue;let angle=Math.atan2(dx,dz);let diff=Math.atan2(Math.sin(angle-state.yaw),Math.cos(angle-state.yaw));let margin=Math.max(.065,.22/dist)+(state.crouch?.015:0);if(Math.abs(diff)<margin&&Math.abs(diff)<best){target=e;best=Math.abs(diff)}}if(target){target.hp-=state.aim?62:48;target.state='chase';target.lastSeen=5;if(target.hp<=0){target.alive=false;target.model.g.rotation.z=1.35;target.model.g.position.y=-.25;toast('УГРОЗА УСТРАНЕНА')}else toast('ПОПАДАНИЕ')}else toast('ПРОМАХ')}
function reload(){if(state.reload||state.ammo===6||state.reserve<=0)return;state.reload=1.3;sound(360,.14);toast('ПЕРЕЗАРЯДКА')}
function heal(){if(state.bandages<1||state.hp>=100){toast(state.bandages?'ЗДОРОВЬЕ ПОЛНОЕ':'НЕТ БИНТОВ');return}state.bandages--;state.hp=Math.min(100,state.hp+45);sound(520,.6);toast('РАНА ПЕРЕВЯЗАНА');save()}
const isTouch=matchMedia('(pointer:coarse)').matches;function start(){if(!state.started){state.started=true;let resumed=load();initAudio();updateObjective();$('hud').style.display='block';$('menu').style.display='none';subtitle('Итан',resumed?'Мара, я рядом. Пойдём.':'Ты уверена, что они ответят? Радио молчит уже три дня.',6);if(!resumed)setTimeout(()=>subtitle('Мара','Пока есть сигнал, есть и надежда. Держись рядом.',6),6500)}if(!isTouch)renderer.domElement.requestPointerLock?.()}
$('start').onclick=start;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.repeat)return;switch(e.key.toLowerCase()){case'e':interact();break;case'r':reload();break;case'h':heal();break;case'c':state.crouch=!state.crouch;toast(state.crouch?'ПРИСЕЛИ · ШАГИ ТИШЕ':'ВСТАЛИ');break;case'm':toast(`КАРТА: РАДИО (-31,-25) · КЛИНИКА (25,-64) · ВЫШКА (0,-116) · ВЫ: (${state.x|0},${state.z|0})`);break;case' ':fire();break}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement||!state.started)return;state.yaw-=e.movementX*.0024;state.pitch=clamp(state.pitch+e.movementY*.0018,-.4,.65)});renderer.domElement.addEventListener('click',()=>{if(!state.started)return;if(document.pointerLockElement===renderer.domElement)fire();else if(!isTouch)renderer.domElement.requestPointerLock?.()});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
const stick=$('stick'),knob=$('knob');stick.addEventListener('pointerdown',e=>{stick.setPointerCapture(e.pointerId);moveStick(e)});stick.addEventListener('pointermove',e=>{if(stick.hasPointerCapture(e.pointerId))moveStick(e)});function moveStick(e){let b=stick.getBoundingClientRect();joy.x=clamp((e.clientX-b.left-b.width/2)/43,-1,1);joy.y=clamp((e.clientY-b.top-b.height/2)/43,-1,1);knob.style.transform=`translate(${joy.x*38}px,${joy.y*38}px)`}stick.addEventListener('pointerup',()=>{joy={x:0,y:0};knob.style.transform=''})
renderer.domElement.addEventListener('pointerdown',e=>{if(isTouch&&e.clientX>innerWidth*.36)lookTouch={id:e.pointerId,x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointermove',e=>{if(lookTouch?.id!==e.pointerId)return;state.yaw-=(e.clientX-lookTouch.x)*.005;state.pitch=clamp(state.pitch+(e.clientY-lookTouch.y)*.003,-.4,.65);lookTouch.x=e.clientX;lookTouch.y=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(lookTouch?.id===e.pointerId)lookTouch=null});
document.querySelectorAll('[data-key]').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();let key=btn.dataset.key;if(key==='fire')fire();else if(key==='run')keys.shift=true;else if(key==='c'){state.crouch=!state.crouch;toast(state.crouch?'ТИХИЙ ШАГ':'ОБЫЧНЫЙ ШАГ')}else if(key==='e')interact();else if(key==='r')reload();else if(key==='h')heal();else if(key==='m')toast(`РАДИО (-31,-25) · КЛИНИКА (25,-64) · ВЫШКА (0,-116)`)});btn.addEventListener('pointerup',()=>{if(btn.dataset.key==='run')keys.shift=false})});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now(),clock=0;function tick(now){requestAnimationFrame(tick);let dt=Math.min(.05,(now-last)/1000);last=now;clock+=dt;if(state.started&&!state.paused&&!state.ended){state.time+=dt;state.shotTime=Math.max(0,state.shotTime-dt);if(state.reload>0){state.reload-=dt;if(state.reload<=0){let n=Math.min(6-state.ammo,state.reserve);state.ammo+=n;state.reserve-=n;save()}}state.alert=Math.max(0,state.alert-dt);state.noise=Math.max(0,state.noise-dt*6);if(state.dialogTime>0){state.dialogTime-=dt;if(state.dialogTime<=0)$('subtitle').textContent=''}
let forward=(keys.w?1:0)-(keys.s?1:0)-joy.y,side=(keys.d?1:0)-(keys.a?1:0)+joy.x;let len=Math.hypot(forward,side);if(len>1){forward/=len;side/=len}let running=keys.shift&&state.stamina>2&&!state.crouch&&len>.15;let speed=state.crouch?2.15:running?7:4;let dx=(Math.sin(state.yaw)*forward+Math.cos(state.yaw)*side)*speed*dt,dz=(Math.cos(state.yaw)*forward-Math.sin(state.yaw)*side)*speed*dt;state.x=clamp(state.x+dx,-105,105);state.z=clamp(state.z+dz,-152,72);state.stamina=clamp(state.stamina+(running?-28:17)*dt,0,100);if(len>.1){state.step+=dt*(running?10:state.crouch?4:7);if(Math.floor(state.step)%5===0&&Math.floor(state.step-dt*7)%5!==0)sound(85,.04,'triangle',.012)}pmodel.g.position.set(state.x,Math.sin(state.step)*.035,state.z);pmodel.g.rotation.y=state.yaw;pmodel.legs.forEach((l,i)=>l.rotation.x=Math.sin(state.step)*(len? .27:0)*(i?1:-1));pmodel.arms.forEach((a,i)=>a.rotation.x=Math.sin(state.step)*(len?.19:0)*(i?-1:1));pmodel.g.scale.y=state.crouch?.76:1;
if(state.companionAlive){let tx=state.x+Math.cos(state.yaw+1.6)*2,tz=state.z+Math.sin(state.yaw+1.6)*2,dd=Math.hypot(tx-companion.g.position.x,tz-companion.g.position.z);if(dd>1.2){let s=Math.min(dd*1.5,dd>12?13:5)*dt;companion.g.position.x+=(tx-companion.g.position.x)/dd*s;companion.g.position.z+=(tz-companion.g.position.z)/dd*s;companion.g.rotation.y=Math.atan2(state.x-companion.g.position.x,state.z-companion.g.position.z)}companion.legs.forEach((l,i)=>l.rotation.x=Math.sin(clock*8)*(dd>1.2?.23:0)*(i?1:-1));}
for(let e of enemies){if(!e.alive)continue;let d=Math.hypot(state.x-e.x,state.z-e.z);let detection=state.crouch?5:running?15:9;if(state.noise>0)detection=Math.max(detection,state.noise);if(d<detection){e.state='chase';e.lastSeen=state.crouch&&d>5?1.5:5;e.target={x:state.x,z:state.z}}else e.lastSeen=Math.max(0,e.lastSeen-dt);if(!e.lastSeen&&e.state==='chase')e.state='search';let tx=e.state==='chase'&&e.target?e.target.x:e.home.x+Math.sin(clock*.3+e.phase)*3,tz=e.state==='chase'&&e.target?e.target.z:e.home.z+Math.cos(clock*.25+e.phase)*3;let td=Math.hypot(tx-e.x,tz-e.z);if(td>.2){let sp=(e.state==='chase'?(e.type==='runner'?4:2.7):.65)*dt;e.x+=(tx-e.x)/td*sp;e.z+=(tz-e.z)/td*sp;e.model.g.rotation.y=Math.atan2(tx-e.x,tz-e.z)}e.model.g.position.set(e.x,Math.sin(clock*7+e.phase)*.02,e.z);e.model.legs.forEach((l,i)=>l.rotation.x=Math.sin(clock*(e.state==='chase'?9:4)+e.phase)*(i?.22:-.22));e.attack=Math.max(0,e.attack-dt);if(d<1.45&&e.attack<=0){state.hp=Math.max(0,state.hp-(e.type==='runner'?19:13));e.attack=1.25;state.hitTime=.6;sound(64,.4,'sawtooth',.13);toast('РАНЕНИЕ · H ПЕРЕВЯЗАТЬ');if(state.hp<=0){state.ended=true;readLetter('СИГНАЛ ОБОРВАЛСЯ','Мара упала среди деревьев. Но у этой истории может быть другой конец.<br><br>Попробуй снова: последнее сохранение позволит вернуться в путь.',()=>{location.reload()})}}}
let nearest=null,nd=3.1;for(let a of interactables){if(!a.active||(a.kind==='medicine'&&state.stage!==1)||(a.kind==='tower'&&state.stage!==2))continue;let d=Math.hypot(state.x-a.x,state.z-a.z);if(d<nd){nd=d;nearest=a}a.glow.position.y=Math.sin(clock*2+a.x)*.12}let names={ammo:'ПОДОБРАТЬ ПАТРОНЫ',bandage:'ПОДОБРАТЬ БИНТ',supplies:'ПОДОБРАТЬ ПРИПАСЫ',note:'ПРОЧИТАТЬ ЗАПИСЬ',medicine:'ЗАБРАТЬ ЛЕКАРСТВО',tower:'ВКЛЮЧИТЬ ПЕРЕДАТЧИК'};$('prompt').style.display=nearest?'block':'none';$('prompt').textContent=nearest?`[E] ${names[nearest.kind]}`:'';
$('hp-number').textContent=state.hp|0;$('hp-bar').style.width=state.hp+'%';$('st-number').textContent=state.stamina|0;$('st-bar').style.width=state.stamina+'%';$('ammo').textContent=`${state.ammo} / ${state.reserve}`;$('bandages').textContent=state.bandages;$('supplies').textContent=state.supplies;$('weather').textContent=`☁ ТУМАН · ${String(6+Math.floor(state.time/240)).padStart(2,'0')}:${String(42+Math.floor(state.time/4)%60).padStart(2,'0')}`;$('status').textContent=state.crouch?'◌ СКРЫТНОСТЬ':enemies.some(e=>e.alive&&e.state==='chase'&&Math.hypot(state.x-e.x,state.z-e.z)<20)?'⚠ ОПАСНОСТЬ':'○ ТИХО';$('vignette').style.background=state.hitTime>0?'radial-gradient(ellipse at center,transparent 20%,#9e221177 100%)':'radial-gradient(ellipse at center,transparent 32%,#06100c88 100%)';state.hitTime=Math.max(0,state.hitTime-dt);if(ambient)ambient.filter.frequency.value=THREE.MathUtils.lerp(ambient.filter.frequency.value,state.alert?700:380,.015);
}let camDist=isTouch?5.8:6.5;let desired=new THREE.Vector3(state.x-Math.sin(state.yaw)*camDist+Math.cos(state.yaw)*1.1,3.2+state.pitch*7,state.z-Math.cos(state.yaw)*camDist-Math.sin(state.yaw)*1.1);camera.position.lerp(desired,Math.min(1,dt*6));camera.lookAt(state.x,1.35,state.z);renderer.render(scene,camera)}requestAnimationFrame(tick);
